import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Language = "en" | "am";
const translations: Record<string, string> = {
  "Inventory Management": "የመድኃኒት ቤት አስተዳደር", "for Pharmacy": "ለመድኃኒት ቤት", "Dashboard": "ዋና ገጽ", "Inventory": "ክምችት", "POS": "ሽያጭ", "Reports": "ሪፖርቶች", "Staff": "ሠራተኞች", "Activity": "እንቅስቃሴ", "Pharmacies": "መድኃኒት ቤቶች", "Account": "መለያ", "Account menu": "የመለያ ምናሌ", "Sign out": "ውጣ", "Back to website": "ወደ ድረ ገጹ ተመለስ", "Made with": "የተሰራው በ", "Designed & built by": "የተነደፈና የተሰራው በ", "owner": "ባለቤት", "pharmacist": "ፋርማሲስት",
  "Page not found": "ገጹ አልተገኘም", "The page you're looking for doesn't exist or has been moved.": "የፈለጉት ገጽ የለም ወይም ተዛውሯል።", "Go home": "ወደ መነሻ ገጽ", "This page didn't load": "ገጹ አልተጫነም", "Something went wrong on our end. You can try refreshing or head back home.": "ችግር ተፈጥሯል። እንደገና ይሞክሩ ወይም ወደ መነሻ ገጽ ይመለሱ።", "Try again": "እንደገና ሞክር",
  "Sign in": "ግባ", "Register your pharmacy": "መድኃኒት ቤትዎን ያስመዝግቡ", "Create an owner account, then name your pharmacy. Your data stays private to your pharmacy.": "የባለቤት መለያ ይፍጠሩ፣ ከዚያም መድኃኒት ቤትዎን ይሰይሙ። መረጃዎ ለመድኃኒት ቤትዎ ብቻ ይታያል።", "Pharmacist accounts are created by the pharmacy owner. Ask the owner for your login credentials.": "የፋርማሲስት መለያዎችን ባለቤቱ ይፈጥራል። የመግቢያ መረጃዎን ከባለቤቱ ይጠይቁ።", "Email": "ኢሜይል", "Password": "የይለፍ ቃል", "Please wait…": "እባክዎ ይጠብቁ…", "Create owner account": "የባለቤት መለያ ፍጠር", "Already have an account? Sign in": "መለያ አለዎት? ይግቡ", "New pharmacy? Register here": "አዲስ መድኃኒት ቤት? እዚህ ይመዝገቡ", "Account created. Set up your pharmacy next.": "መለያ ተፈጥሯል። አሁን መድኃኒት ቤትዎን ያዘጋጁ።", "Authentication failed": "መግባት አልተሳካም",
  "Set up your pharmacy": "መድኃኒት ቤትዎን ያዘጋጁ", "Your pharmacy gets its own private inventory, sales and staff. Nothing is shared with other pharmacies.": "መድኃኒት ቤትዎ የራሱ የግል ክምችት፣ ሽያጭ እና ሠራተኞች ይኖሩታል።", "Pharmacy name": "የመድኃኒት ቤት ስም", "Choose your plan": "እቅድዎን ይምረጡ", "birr/month": "ብር/ወር", "14 days free. After that, pay your provider monthly to keep access.": "14 ቀናት በነጻ። ከዚያ በኋላ አገልግሎቱን ለመቀጠል በየወሩ ይክፈሉ።", "Create pharmacy": "መድኃኒት ቤት ፍጠር", "Creating…": "በመፍጠር ላይ…", "Pharmacy name is required": "የመድኃኒት ቤት ስም ያስፈልጋል", "Please choose a plan": "እባክዎ እቅድ ይምረጡ", "Pharmacy created — your 14-day free trial has started": "መድኃኒት ቤትዎ ተፈጥሯል — የ14 ቀን ነጻ ሙከራዎ ተጀምሯል", "Could not create pharmacy": "መድኃኒት ቤት መፍጠር አልተቻለም", "Medicines, batches, expiry & barcodes": "መድኃኒቶች፣ ባቾች፣ የሚያበቃበት ቀን እና ባርኮድ", "Stock in / stock out with reasons": "ከምክንያት ጋር ክምችት ጨምር / ቀንስ", "Low-stock & expiry alerts": "የአነስተኛ ክምችትና የማብቂያ ማስጠንቀቂያ", "Inventory reports & staff accounts": "የክምችት ሪፖርቶችና የሠራተኛ መለያዎች", "Everything in Inventory": "በክምችት እቅድ ያለው ሁሉ", "Point of sale with receipts (works offline)": "ከደረሰኝ ጋር ሽያጭ (ያለ ኢንተርኔትም ይሰራል)", "Daily/weekly sales, VAT & profit reports": "ዕለታዊ/ሳምንታዊ ሽያጭ፣ ታክስና ትርፍ ሪፖርቶች",
  "Overview of sales, profit, stock and alerts": "የሽያጭ፣ ትርፍ፣ ክምችትና ማስጠንቀቂያዎች እይታ", "New sale": "አዲስ ሽያጭ", "Loading…": "በመጫን ላይ…", "Today's revenue": "የዛሬ ገቢ", "Today's profit": "የዛሬ ትርፍ", "7-day revenue": "የ7 ቀን ገቢ", "Inventory value": "የክምችት ዋጋ", "Last 7 days revenue": "ያለፉት 7 ቀናት ገቢ", "Today by payment": "የዛሬ ክፍያዎች", "No sales yet today.": "ዛሬ ሽያጭ የለም።", "Total": "ድምር", "Top sellers (30d)": "በ30 ቀን ብዙ የተሸጡ", "No sales yet.": "እስካሁን ሽያጭ የለም።", "Low stock": "አነስተኛ ክምችት", "All stocked up.": "ክምችት በቂ ነው።", "Manage inventory": "ክምችት አስተዳድር", "Expiring ≤ 60d": "በ60 ቀናት ውስጥ የሚያበቃ", "Nothing expiring soon.": "በቅርቡ የሚያበቃ የለም።", "est.": "ግምት", "items": "ዕቃዎች", "sales": "ሽያጮች",
  "Manage your medicine stock": "የመድኃኒት ክምችትዎን ያስተዳድሩ", "Add Medicine": "መድኃኒት ጨምር", "Edit medicine": "መድኃኒት አርትዕ", "Add medicine": "መድኃኒት ጨምር", "Fields marked * are required.": "በ * የተለዩ መስኮች አስፈላጊ ናቸው።", "Name *": "ስም *", "Brand": "ብራንድ", "Category": "ምድብ", "Select or type": "ይምረጡ ወይም ይጻፉ", "+ New category…": "+ አዲስ ምድብ…", "Type new category name": "የአዲሱን ምድብ ስም ይጻፉ", "Batch #": "ባች ቁጥር", "Barcode": "ባርኮድ", "Quantity *": "ብዛት *", "Reorder level": "የድጋሚ ትዕዛዝ መጠን", "Alert me when stock drops to this number. Helps you reorder before running out.": "ክምችቱ እዚህ መጠን ሲደርስ ያሳውቀኛል።", "Cost price (ETB)": "የግዢ ዋጋ (ብር)", "What you pay the supplier. Used to calculate profit. Owner-only.": "ለአቅራቢው የሚከፍሉት። ትርፍን ለማስላት ያገለግላል። ለባለቤት ብቻ።", "Unit price (ETB) *": "የመሸጫ ዋጋ (ብር) *", "Only the pharmacy owner can change prices.": "ዋጋ መቀየር የሚችለው ባለቤቱ ብቻ ነው።", "Expiry date *": "የማብቂያ ቀን *", "Cancel": "ሰርዝ", "Saving…": "በማስቀመጥ ላይ…", "Update": "አዘምን", "Add": "ጨምር", "Total items": "ጠቅላላ ዕቃዎች", "Expiring < 60d": "በ60 ቀን የሚያበቃ", "Stock value": "የክምችት ዋጋ", "Search by name, brand, batch…": "በስም፣ ብራንድ ወይም ባች ይፈልጉ…", "Filter by category": "በምድብ አጣራ", "All categories": "ሁሉም ምድቦች", "Medicine": "መድኃኒት", "Batch": "ባች", "Qty": "ብዛት", "Price (ETB)": "ዋጋ (ብር)", "Expiry": "ማብቂያ", "No medicines found": "መድኃኒት አልተገኘም", "Low": "አነስተኛ", "Expired": "ጊዜው ያለፈ", "Soon": "በቅርቡ", "Stock in": "ክምችት ጨምር", "Stock out": "ክምችት ቀንስ", "Name is required": "ስም ያስፈልጋል", "Quantity is required": "ብዛት ያስፈልጋል", "Unit price is required": "የመሸጫ ዋጋ ያስፈልጋል", "Expiry date is required": "የማብቂያ ቀን ያስፈልጋል", "Quantity cannot be negative": "ብዛት ከዜሮ በታች መሆን አይችልም", "Unit price cannot be negative": "ዋጋ ከዜሮ በታች መሆን አይችልም", "Medicine updated": "መድኃኒቱ ተዘምኗል", "Medicine added": "መድኃኒቱ ተጨምሯል", "Deleted": "ተሰርዟል", "Save failed": "ማስቀመጥ አልተሳካም", "No pharmacy assigned to your account": "ለመለያዎ መድኃኒት ቤት አልተመደበም",
  "New delivery from supplier": "ከአቅራቢ አዲስ እቃ", "Returned by customer": "ከደንበኛ የተመለሰ", "Count correction (add)": "ቆጠራ ማስተካከያ (ጨምር)", "Sold / dispensed": "የተሸጠ / የተሰጠ", "Damaged": "የተበላሸ", "Expired — thrown away": "ጊዜው ያለፈ — የተወገደ", "Count correction (remove)": "ቆጠራ ማስተካከያ (ቀንስ)", "Enter a quantity above 0": "ከዜሮ በላይ ብዛት ያስገቡ", "Quantity": "ብዛት", "Reason": "ምክንያት", "Note (optional)": "ማስታወሻ (አማራጭ)", "Supplier, invoice no., customer…": "አቅራቢ፣ የደረሰኝ ቁጥር፣ ደንበኛ…", "Save": "አስቀምጥ",
  "Point of Sale": "የሽያጭ መስኮት", "Tap a medicine to add it to the cart": "መድኃኒት ለመጨመር ይንኩ", "Search medicines or scan barcode…": "መድኃኒት ይፈልጉ ወይም ባርኮድ ያንብቡ…", "No medicines available": "መድኃኒት የለም", "Current Sale": "የአሁኑ ሽያጭ", "Cart is empty": "የሽያጭ ዝርዝሩ ባዶ ነው", "Cashier name": "የገንዘብ ተቀባይ ስም", "Cash": "ጥሬ ገንዘብ", "Telebirr": "ቴሌብር", "CBE": "ንግድ ባንክ", "Complete Sale": "ሽያጩን ጨርስ", "Processing…": "በማስኬድ ላይ…", "Sale Completed": "ሽያጩ ተጠናቋል", "Print": "አትም", "New Sale": "አዲስ ሽያጭ", "Not enough stock": "በቂ ክምችት የለም", "Sale completed": "ሽያጩ ተጠናቋል", "Checkout failed": "ሽያጩ አልተሳካም", "Saved offline — will upload when internet returns": "ያለ ኢንተርኔት ተቀምጧል — ኢንተርኔት ሲመለስ ይላካል",
  "Sales": "ሽያጭ", "Excel (CSV)": "ኤክሴል (CSV)", "From": "ከ", "To": "እስከ", "VAT % (included in prices)": "ተ.እ.ታ % (በዋጋ ውስጥ የተካተተ)", "Today": "ዛሬ", "7 days": "7 ቀናት", "30 days": "30 ቀናት", "Daily": "ዕለታዊ", "Weekly": "ሳምንታዊ", "Revenue": "ገቢ", "VAT collected": "የተሰበሰበ ተ.እ.ታ", "Cost of goods": "የእቃ ወጪ", "Gross profit": "ጠቅላላ ትርፍ", "VAT": "ተ.እ.ታ", "Cost": "ወጪ", "Profit": "ትርፍ", "Date": "ቀን", "Week of": "የሳምንቱ መጀመሪያ", "No sales in this period.": "በዚህ ጊዜ ሽያጭ የለም።", "By payment method": "በክፍያ ዓይነት", "No data.": "መረጃ የለም።", "Best sellers & profit": "ብዙ የተሸጡና ትርፍ", "Profit uses each medicine's current cost price. VAT is calculated as the share of the selling price at the rate above.": "ትርፍ የሚሰላው አሁን ባለው የግዢ ዋጋ ነው። ተ.እ.ታ ከመሸጫ ዋጋው ውስጥ ይሰላል።", "Stock value (cost)": "የክምችት ዋጋ (የግዢ)", "Stock value (selling price)": "የክምችት ዋጋ (የመሸጫ)", "Units in / out": "የገባ / የወጣ ብዛት", "Losses (damaged + expired)": "ኪሳራ (የተበላሸ + ጊዜው ያለፈ)", "Stock in / out by reason": "የክምችት ለውጥ በምክንያት", "No stock movements in this period.": "በዚህ ጊዜ የክምችት ለውጥ የለም።", "Expired but still in stock": "ጊዜው ያለፈ ነገር ግን በክምችት ያለ", "Stock movements": "የክምችት ለውጦች", "Change": "ለውጥ", "By": "በ", "No movements yet. Use the Stock in / Stock out buttons on the Inventory page.": "እስካሁን ለውጥ የለም። በክምችት ገጹ የመጨመር/መቀነስ አዝራሮችን ይጠቀሙ።", "in this period": "በዚህ ጊዜ", "at cost price": "በግዢ ዋጋ",
  "Staff accounts": "የሠራተኛ መለያዎች", "Create login accounts for your pharmacists. They get inventory + POS access only.": "ለፋርማሲስቶችዎ መለያ ይፍጠሩ። የክምችትና የሽያጭ መዳረሻ ይኖራቸዋል።", "Create pharmacist": "ፋርማሲስት ፍጠር", "Create pharmacist account": "የፋርማሲስት መለያ ፍጠር", "Temporary password (min 6 chars)": "ጊዜያዊ የይለፍ ቃል (ቢያንስ 6 ፊደላት)", "Share this with the pharmacist": "ይህን ለፋርማሲስቱ ያጋሩ", "The pharmacist gets a confirmation email and can sign in after clicking the link.": "ፋርማሲስቱ የማረጋገጫ ኢሜይል ይቀበላል፤ አገናኙን ከተጫነ በኋላ መግባት ይችላል።", "Create account": "መለያ ፍጠር", "Role": "ሚና", "Created": "የተፈጠረበት", "No accounts yet.": "እስካሁን መለያ የለም።", "awaiting email confirmation": "የኢሜይል ማረጋገጫ በመጠባበቅ ላይ", "Password must be at least 6 characters": "የይለፍ ቃል ቢያንስ 6 ፊደላት መሆን አለበት", "That email is already registered": "ይህ ኢሜይል አስቀድሞ ተመዝግቧል", "Access removed": "መዳረሻ ተወግዷል", "Failed to load staff": "ሠራተኞችን መጫን አልተሳካም", "Failed to create account": "መለያ መፍጠር አልተሳካም", "Failed to delete": "ማስወገድ አልተሳካም",
  "Activity log": "የእንቅስቃሴ መዝገብ", "Who added, edited, or deleted medicines.": "መድኃኒቶችን ማን እንደጨመረ፣ እንዳርትዕ ወይም እንደሰረዘ።", "When": "መቼ", "Action": "ድርጊት", "Details": "ዝርዝር", "No activity yet.": "እስካሁን እንቅስቃሴ የለም።", "create": "ፍጠር", "update": "አዘምን", "delete": "ሰርዝ", "added a new medicine": "አዲስ መድኃኒት ጨመረ", "deleted the medicine": "መድኃኒቱን ሰረዘ", "updated the medicine": "መድኃኒቱን አዘመነ",
  "Administrators only": "ለአስተዳዳሪዎች ብቻ", "This page is reserved for the software provider.": "ይህ ገጽ ለሶፍትዌር አቅራቢው ብቻ ነው።", "Every pharmacy using the software, their subscription and payments.": "ሶፍትዌሩን የሚጠቀሙ መድኃኒት ቤቶች፣ እቅዳቸውና ክፍያቸው።", "With active access": "ንቁ መዳረሻ ያላቸው", "Monthly recurring": "ወርሃዊ ገቢ", "No pharmacies registered yet.": "እስካሁን መድኃኒት ቤት አልተመዘገበም።", "Plan": "እቅድ", "Inventory only": "ክምችት ብቻ", "Inventory + POS": "ክምችት + ሽያጭ", "Inventory only · 3,900 birr": "ክምችት ብቻ · 3,900 ብር", "Inventory + POS · 6,900 birr": "ክምችት + ሽያጭ · 6,900 ብር", "Monthly fee (birr)": "ወርሃዊ ክፍያ (ብር)", "Status": "ሁኔታ", "Trial": "ሙከራ", "Active": "ንቁ", "Past due": "ክፍያው ያለፈ", "Suspended": "የታገደ", "trial": "ሙከራ", "active": "ንቁ", "past due": "ክፍያው ያለፈ", "suspended": "የታገደ", "Record payment": "ክፍያ መዝግብ", "Amount received": "የተቀበለው መጠን", "Months to extend": "የሚጨመሩ ወራት", "Bank transfer ref…": "የባንክ ዝውውር ማጣቀሻ…", "Access is extended from the current end date and the pharmacy is set to active.": "መዳረሻው ከአሁኑ ማብቂያ ቀን ይራዘማል፣ መድኃኒት ቤቱም ንቁ ይሆናል።", "Save payment": "ክፍያ አስቀምጥ", "Payment recorded and access extended": "ክፍያው ተመዝግቦ መዳረሻው ተራዝሟል", "Monthly fee updated": "ወርሃዊ ክፍያው ተዘምኗል",
};

const LanguageContext = createContext<{ language: Language; setLanguage: (value: Language) => void; t: (text: string) => string }>({ language: "en", setLanguage: () => {}, t: (text) => text });
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");
  useEffect(() => { try { if (localStorage.getItem("pharmacy-language") === "am") setLanguage("am"); } catch { /* private browsing */ } }, []);
  useEffect(() => { document.documentElement.lang = language; try { localStorage.setItem("pharmacy-language", language); } catch { /* private browsing */ } }, [language]);
  return <LanguageContext.Provider value={{ language, setLanguage, t: (text) => language === "am" ? translations[text] ?? text : text }}>{children}</LanguageContext.Provider>;
}
export const useLanguage = () => useContext(LanguageContext);
